# c:\Users\Robi\Desktop\Shega Skin Studio\docker-compose.yml

services:
  # 1. Frontend Service (React)
  frontend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # 2. Backend Service (Node.js)
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SUPER_ADMIN_EMAIL=${SUPER_ADMIN_EMAIL}
      - SUPER_ADMIN_PASSWORD=${SUPER_ADMIN_PASSWORD}
    depends_on:
      - mongo

  # 3. Database Service (MongoDB)
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
